/*
 * generated by Xtext 2.42.0
 */
package gse.xtext.assignment.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.xbase.testing.CompilationTestHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(AccessPoliciesInjectorProvider)
class AccessPoliciesCodeGenTest {

	@Inject extension CompilationTestHelper

	private def assertIsAllowed(String code, String actor, String operation, String asset) {
		assertIsAllowed(code, actor, operation, asset, true)
	}

	private def assertIsDenied(String code, String actor, String operation, String asset) {
		assertIsAllowed(code, actor, operation, asset, false)
	}

	private def assertIsAllowed(String code, String actor, String operation, String asset, boolean assertAllowed) {
		code.compile [ result |
			Assertions.assertNotNull(result.getGeneratedCode("SecurityEvaluator"))

			// Verify there are no Java compilation errors
			result.assertNoErrors

			// Load the generated class using reflection
			val clazz = result.getCompiledClass("SecurityEvaluator")
			val isAllowedMethod = clazz.getMethod(
				"isAllowed",
				typeof(String),
				typeof(String),
				typeof(String)
			)

			// Define a local helper lambda to simplify invocations
			val isAllowed = [ String myActor, String myOperation, String myAsset |
				isAllowedMethod.invoke(null, myActor, myOperation, myAsset) as Boolean
			]

			val boolean allowed = isAllowed.apply(actor, operation, asset)
			if (assertAllowed) {
				Assertions.assertTrue(allowed)
			} else {
				Assertions.assertFalse(allowed)
			}
		]

	}

	val String example = '''
		user Resident
		device FrontDoor
		command lock
		
		home_profile NightMode {
		    for_user Resident {
		        grant lock on FrontDoor
		    }
		}
	'''

	// Simple declarations: actors, assets, and operations
	@Test
	def void testHasClassSecurityEvaluator() {
		example.compile [ result |
			Assertions.assertNotNull(result.getGeneratedCode("SecurityEvaluator"))
		]
	}

	@Test
	def void testCompilesSecurityEvaluator() {
		example.compile [ result |
			Assertions.assertNotNull(result.getGeneratedCode("SecurityEvaluator"))

			// Verify there are no Java compilation errors
			result.assertNoErrors

			// Load the generated class using reflection
			Assertions.assertNotNull(result.getCompiledClass("SecurityEvaluator"))
		]
	}

	@Test
	def void testHasMethodIsAllowed() {
		example.compile [ result |
			Assertions.assertNotNull(result.getGeneratedCode("SecurityEvaluator"))

			// Verify there are no Java compilation errors
			result.assertNoErrors

			// Load the generated class using reflection
			val clazz = result.getCompiledClass("SecurityEvaluator")
			val isAllowedMethod = clazz.getMethod(
				"isAllowed",
				typeof(String),
				typeof(String),
				typeof(String)
			)

			Assertions.assertNotNull(isAllowedMethod)
		]
	}

	@Test
	def void testPositivePolicy() {
		assertIsAllowed(example, "Resident", "lock", "FrontDoor")
	}

	@Test
	def void testPositivePolicyMultiple() {
		assertIsAllowed(example, "Resident", "lock", "FrontDoor")
	}

	@Test
	def void testPositivePolicyWrongActor() {
		val code = '''
		user Resident
		user Alice
		device FrontDoor
		device Thermostat
		command lock
		
		home_profile NightMode {
		    for_user Resident {
		        grant lock on FrontDoor
		    }
		}
		home_profile Data_Access {
		    for_user Alice {
		        grant lock on Thermostat
		    }
		}
		'''
		assertIsDenied(code, "Alice", "lock", "FrontDoor")
		assertIsAllowed(code, "Resident", "lock", "FrontDoor")
		
		assertIsDenied(code, "Resident", "lock", "Thermostat")
		assertIsAllowed(code, "Alice", "lock", "Thermostat")
	}

	@Test
	def void testInheritance() {
		val code = '''
			user Resident
			user Alice inherits Resident
			device FrontDoor
			command lock
			command unlock
			
			home_profile NightMode {
			    for_user Resident {
			        grant lock on FrontDoor
			    }
			}
		'''
		assertIsDenied(code, "Alice", "unlock", "FrontDoor")
		assertIsAllowed(code, "Alice", "lock", "FrontDoor")
	}

	@Test
	def void testInheritanceTransitive() {
		val code = '''
			user Resident
			user Alice inherits Resident
			user Bob inherits Alice
			device FrontDoor
			command lock
			command unlock
			
			home_profile NightMode {
			    for_user Resident {
			        grant lock on FrontDoor
			    }		    
			}
		'''
		assertIsDenied(code, "Bob", "unlock", "FrontDoor")
		assertIsAllowed(code, "Bob", "lock", "FrontDoor")
	}

}

