/*
 * generated by Xtext 2.42.0
 */
package gse.xtext.assignment.tests

import com.google.inject.Inject
import gse.xtext.assignment.accessPolicies.Model
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.eclipse.xtext.testing.validation.ValidationTestHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(AccessPoliciesInjectorProvider)
class AccessPoliciesParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	@Inject
	ValidationTestHelper validationHelper
	
	
	private def parseTest(String string, boolean valid) {
		val Model result = parseHelper.parse(string)
		if (valid) {
			Assertions.assertNotNull(result)			
			val errors = result.eResource().errors
			val issues = validationHelper.validate(result)
			Assertions.assertTrue(errors.isEmpty, '''Parsing of "«string»" failed with unexpected errors: «errors.join(", ")»''')
			Assertions.assertTrue(issues.isEmpty, '''Parsing of "«string»" failed with unexpected issues: «issues.join(", ")»''')
		} else {
			val errors = result.eResource().errors
			val issues = validationHelper.validate(result)
			Assertions.assertFalse(errors.isEmpty && issues.isEmpty, '''Unexpectedly parsed "«string»" which is invalid.''')
		}
	}	
	
	private def parseTest(String string) {
		parseTest(string, true);
	}

	// Simple declarations: actors, assets, and operations
	
	@Test
	def void parseActor() {
		parseTest('''
		user Resident
		''')
	}
	
	@Test
	def void parseActorsInherit() {
		parseTest('''
		user Resident
		user Alice inherits Resident
		''')
	}
	
	@Test
	def void parseActorsBadInherit() {
		parseTest('''
		user Resident
		user Alice inherits XXX
		''', false)
	}
	
	
	@Test
	def void parseAsset() {
		parseTest('''
		device FrontDoor
		''')
	}

	@Test
	def void parseAssets() {
		parseTest('''
		device FrontDoor
		device Thermostat
		''')
	}
	
	@Test
	def void parseOperation() {
		parseTest('''
		command lock
		''')
	}
	
	@Test
	def void parseActorAssetOperation() {
		parseTest('''
		user Resident
		command lock
		device FrontDoor
		user Bob inherits Resident
		''')
	}
	
	// Policies
	@Test
	def void parseEmptyPolicy() {
		parseTest('''
		home_profile NightMode {
		}
		''')
	}
	@Test
	def void parsePolicyWithActor() {
		parseTest('''
		user Resident
		home_profile NightMode {
			for_user Resident {
			}
		}
		''')
	}
	
	@Test
	def void parsePolicyWithActors() {
		parseTest('''
		user Resident
		user Alice
		home_profile NightMode {
			for_user Resident {
			}
			for_user Alice {
			}
		}
		''')
	}

	@Test
	def void parsePolicyWithActorAndRule() {
		parseTest('''
		user Resident
		device FrontDoor
		command lock
		
		home_profile NightMode {
		    for_user Resident {
		        grant lock on FrontDoor
		    }
		}
		''')
	}
	
	@Test
	def void parsePolicyWithActorAndRules() {
		parseTest('''
		user Resident
		device FrontDoor
		command lock
		command unlock
		
		home_profile NightMode {
		    for_user Resident {
		        grant lock on FrontDoor
		        revoke unlock on FrontDoor
		    }
		}
		''')
	}
	
	@Test
	def void parseFullScenario() {
		parseTest('''
		// Actor hierarchy
		user Resident
		user Alice inherits Resident
		user Bob inherits Resident
		
		// Assets
		device FrontDoor
		device Thermostat
		
		// Operations
		command lock
		command unlock
		command set_temperature
		
		// Security Policy
		home_profile NightMode {
		    for_user Resident {
		        grant lock on FrontDoor
		        revoke unlock on FrontDoor
		    }
		
		    for_user Alice {
		        grant lock on Thermostat
		        revoke set_temperature on Thermostat
		    }
		
		    for_user Bob {
		        grant unlock on FrontDoor
		        grant set_temperature on Thermostat
		    }
		}
		''')
	}
	
}
