/*
 * generated by Xtext 2.42.0
 */
package gse.xtext.assignment.tests

import com.google.inject.Inject
import gse.xtext.assignment.accessPolicies.Model
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.eclipse.xtext.testing.validation.ValidationTestHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(AccessPoliciesInjectorProvider)
class AccessPoliciesParsingTest {
	@Inject
	ParseHelper<Model> parseHelper
	
	@Inject
	ValidationTestHelper validationHelper
	
	
	private def parseTest(String string, boolean valid) {
		val Model result = parseHelper.parse(string)
		if (valid) {
			Assertions.assertNotNull(result)			
			val errors = result.eResource().errors
			val issues = validationHelper.validate(result)
			Assertions.assertTrue(errors.isEmpty, '''Parsing of "«string»" failed with unexpected errors: «errors.join(", ")»''')
			Assertions.assertTrue(issues.isEmpty, '''Parsing of "«string»" failed with unexpected issues: «issues.join(", ")»''')
		} else {
			val errors = result.eResource().errors
			val issues = validationHelper.validate(result)
			Assertions.assertFalse(errors.isEmpty && issues.isEmpty, '''Unexpectedly parsed "«string»" which is invalid.''')
		}
	}	
	
	private def parseTest(String string) {
		parseTest(string, true);
	}

	// Simple declarations: actors, assets, and operations
	
	@Test
	def void parseActor() {
		parseTest('''
		{{keyword_actor}} {{example_actor1}}
		''')
	}
	
	@Test
	def void parseActorsInherit() {
		parseTest('''
		{{keyword_actor}} {{example_actor1}}
		{{keyword_actor}} {{example_actor2}} inherits {{example_actor1}}
		''')
	}
	
	@Test
	def void parseActorsBadInherit() {
		parseTest('''
		{{keyword_actor}} {{example_actor1}}
		{{keyword_actor}} {{example_actor2}} inherits XXX
		''', false)
	}
	
	
	@Test
	def void parseAsset() {
		parseTest('''
		{{keyword_asset}} {{example_asset1}}
		''')
	}

	@Test
	def void parseAssets() {
		parseTest('''
		{{keyword_asset}} {{example_asset1}}
		{{keyword_asset}} {{example_asset2}}
		''')
	}
	
	@Test
	def void parseOperation() {
		parseTest('''
		{{keyword_operation}} {{example_operation1}}
		''')
	}
	
	@Test
	def void parseActorAssetOperation() {
		parseTest('''
		{{keyword_actor}} {{example_actor1}}
		{{keyword_operation}} {{example_operation1}}
		{{keyword_asset}} {{example_asset1}}
		{{keyword_actor}} {{example_actor3}} inherits {{example_actor1}}
		''')
	}
	
	// Policies
	@Test
	def void parseEmptyPolicy() {
		parseTest('''
		{{keyword_policy}} {{example_policy}} {
		}
		''')
	}
	@Test
	def void parsePolicyWithActor() {
		parseTest('''
		{{keyword_actor}} {{example_actor1}}
		{{keyword_policy}} {{example_policy}} {
			{{keyword_scope}} {{example_actor1}} {
			}
		}
		''')
	}
	
	@Test
	def void parsePolicyWithActors() {
		parseTest('''
		{{keyword_actor}} {{example_actor1}}
		{{keyword_actor}} {{example_actor2}}
		{{keyword_policy}} {{example_policy}} {
			{{keyword_scope}} {{example_actor1}} {
			}
			{{keyword_scope}} {{example_actor2}} {
			}
		}
		''')
	}

	@Test
	def void parsePolicyWithActorAndRule() {
		parseTest('''
		{{keyword_actor}} {{example_actor1}}
		{{keyword_asset}} {{example_asset1}}
		{{keyword_operation}} {{example_operation1}}
		
		{{keyword_policy}} {{example_policy}} {
		    {{keyword_scope}} {{example_actor1}} {
		        {{keyword_allow}} {{example_operation1}} on {{example_asset1}}
		    }
		}
		''')
	}
	
	@Test
	def void parsePolicyWithActorAndRules() {
		parseTest('''
		{{keyword_actor}} {{example_actor1}}
		{{keyword_asset}} {{example_asset1}}
		{{keyword_operation}} {{example_operation1}}
		{{keyword_operation}} {{example_operation2}}
		
		{{keyword_policy}} {{example_policy}} {
		    {{keyword_scope}} {{example_actor1}} {
		        {{keyword_allow}} {{example_operation1}} on {{example_asset1}}
		        {{keyword_deny}} {{example_operation2}} on {{example_asset1}}
		    }
		}
		''')
	}
	
	@Test
	def void parseFullScenario() {
		parseTest('''
		// Actor hierarchy
		{{keyword_actor}} {{example_actor1}}
		{{keyword_actor}} {{example_actor2}} inherits {{example_actor1}}
		{{keyword_actor}} {{example_actor3}} inherits {{example_actor1}}
		
		// Assets
		{{keyword_asset}} {{example_asset1}}
		{{keyword_asset}} {{example_asset2}}
		
		// Operations
		{{keyword_operation}} {{example_operation1}}
		{{keyword_operation}} {{example_operation2}}
		{{keyword_operation}} {{example_operation3}}
		
		// Security Policy
		{{keyword_policy}} {{example_policy}} {
		    {{keyword_scope}} {{example_actor1}} {
		        {{keyword_allow}} {{example_operation1}} on {{example_asset1}}
		        {{keyword_deny}} {{example_operation2}} on {{example_asset1}}
		    }
		
		    {{keyword_scope}} {{example_actor2}} {
		        {{keyword_allow}} {{example_operation1}} on {{example_asset2}}
		        {{keyword_deny}} {{example_operation3}} on {{example_asset2}}
		    }
		
		    {{keyword_scope}} {{example_actor3}} {
		        {{keyword_allow}} {{example_operation2}} on {{example_asset1}}
		        {{keyword_allow}} {{example_operation3}} on {{example_asset2}}
		    }
		}
		''')
	}
	
}
