/*
 * generated by Xtext 2.42.0
 */
package gse.xtext.assignment.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.xbase.testing.CompilationTestHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(AccessPoliciesInjectorProvider)
class AccessPoliciesCodeGenTest {

	@Inject extension CompilationTestHelper

	private def assertIsAllowed(String code, String actor, String operation, String asset) {
		assertIsAllowed(code, actor, operation, asset, true)
	}

	private def assertIsDenied(String code, String actor, String operation, String asset) {
		assertIsAllowed(code, actor, operation, asset, false)
	}

	private def assertIsAllowed(String code, String actor, String operation, String asset, boolean assertAllowed) {
		code.compile [ result |
			Assertions.assertNotNull(result.getGeneratedCode("SecurityEvaluator"))

			// Verify there are no Java compilation errors
			result.assertNoErrors

			// Load the generated class using reflection
			val clazz = result.getCompiledClass("SecurityEvaluator")
			val isAllowedMethod = clazz.getMethod(
				"isAllowed",
				typeof(String),
				typeof(String),
				typeof(String)
			)

			// Define a local helper lambda to simplify invocations
			val isAllowed = [ String myActor, String myOperation, String myAsset |
				isAllowedMethod.invoke(null, myActor, myOperation, myAsset) as Boolean
			]

			val boolean allowed = isAllowed.apply(actor, operation, asset)
			if (assertAllowed) {
				Assertions.assertTrue(allowed)
			} else {
				Assertions.assertFalse(allowed)
			}
		]

	}

	val String example = '''
		{{keyword_actor}} {{example_actor1}}
		{{keyword_asset}} {{example_asset1}}
		{{keyword_operation}} {{example_operation1}}
		
		{{keyword_policy}} {{example_policy}} {
		    {{keyword_scope}} {{example_actor1}} {
		        {{keyword_allow}} {{example_operation1}} on {{example_asset1}}
		    }
		}
	'''

	// Simple declarations: actors, assets, and operations
	@Test
	def void testHasClassSecurityEvaluator() {
		example.compile [ result |
			Assertions.assertNotNull(result.getGeneratedCode("SecurityEvaluator"))
		]
	}

	@Test
	def void testCompilesSecurityEvaluator() {
		example.compile [ result |
			Assertions.assertNotNull(result.getGeneratedCode("SecurityEvaluator"))

			// Verify there are no Java compilation errors
			result.assertNoErrors

			// Load the generated class using reflection
			Assertions.assertNotNull(result.getCompiledClass("SecurityEvaluator"))
		]
	}

	@Test
	def void testHasMethodIsAllowed() {
		example.compile [ result |
			Assertions.assertNotNull(result.getGeneratedCode("SecurityEvaluator"))

			// Verify there are no Java compilation errors
			result.assertNoErrors

			// Load the generated class using reflection
			val clazz = result.getCompiledClass("SecurityEvaluator")
			val isAllowedMethod = clazz.getMethod(
				"isAllowed",
				typeof(String),
				typeof(String),
				typeof(String)
			)

			Assertions.assertNotNull(isAllowedMethod)
		]
	}

	@Test
	def void testPositivePolicy() {
		assertIsAllowed(example, "{{example_actor1}}", "{{example_operation1}}", "{{example_asset1}}")
	}

	@Test
	def void testPositivePolicyMultiple() {
		assertIsAllowed(example, "{{example_actor1}}", "{{example_operation1}}", "{{example_asset1}}")
	}

	@Test
	def void testPositivePolicyWrongActor() {
		val code = '''
		{{keyword_actor}} {{example_actor1}}
		{{keyword_actor}} {{example_actor2}}
		{{keyword_asset}} {{example_asset1}}
		{{keyword_asset}} {{example_asset2}}
		{{keyword_operation}} {{example_operation1}}
		
		{{keyword_policy}} {{example_policy}} {
		    {{keyword_scope}} {{example_actor1}} {
		        {{keyword_allow}} {{example_operation1}} on {{example_asset1}}
		    }
		}
		{{keyword_policy}} Data_Access {
		    {{keyword_scope}} {{example_actor2}} {
		        {{keyword_allow}} {{example_operation1}} on {{example_asset2}}
		    }
		}
		'''
		assertIsDenied(code, "{{example_actor2}}", "{{example_operation1}}", "{{example_asset1}}")
		assertIsAllowed(code, "{{example_actor1}}", "{{example_operation1}}", "{{example_asset1}}")
		
		assertIsDenied(code, "{{example_actor1}}", "{{example_operation1}}", "{{example_asset2}}")
		assertIsAllowed(code, "{{example_actor2}}", "{{example_operation1}}", "{{example_asset2}}")
	}

	@Test
	def void testInheritance() {
		val code = '''
			{{keyword_actor}} {{example_actor1}}
			{{keyword_actor}} {{example_actor2}} inherits {{example_actor1}}
			{{keyword_asset}} {{example_asset1}}
			{{keyword_operation}} {{example_operation1}}
			{{keyword_operation}} {{example_operation2}}
			
			{{keyword_policy}} {{example_policy}} {
			    {{keyword_scope}} {{example_actor1}} {
			        {{keyword_allow}} {{example_operation1}} on {{example_asset1}}
			    }
			}
		'''
		assertIsDenied(code, "{{example_actor2}}", "{{example_operation2}}", "{{example_asset1}}")
		assertIsAllowed(code, "{{example_actor2}}", "{{example_operation1}}", "{{example_asset1}}")
	}

	@Test
	def void testInheritanceTransitive() {
		val code = '''
			{{keyword_actor}} {{example_actor1}}
			{{keyword_actor}} {{example_actor2}} inherits {{example_actor1}}
			{{keyword_actor}} {{example_actor3}} inherits {{example_actor2}}
			{{keyword_asset}} {{example_asset1}}
			{{keyword_operation}} {{example_operation1}}
			{{keyword_operation}} {{example_operation2}}
			
			{{keyword_policy}} {{example_policy}} {
			    {{keyword_scope}} {{example_actor1}} {
			        {{keyword_allow}} {{example_operation1}} on {{example_asset1}}
			    }		    
			}
		'''
		assertIsDenied(code, "{{example_actor3}}", "{{example_operation2}}", "{{example_asset1}}")
		assertIsAllowed(code, "{{example_actor3}}", "{{example_operation1}}", "{{example_asset1}}")
	}

}

